### ISSUE TITLE
Replace useState with useRef

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix-react-native-example#6]
## Motivation

Read docs for useRef. 
Review the code we have in App.js
https://github.com/aerogear/offix-react-native-example/blob/9a546194ce085e82cd3cd921efbec933e9a490ab/offixapp/src/App.js#L50-L53
Swap setState with useRef

**Comment by wtrocki** [comment]
@mmusil FYI

**Comment by mmusil** [comment]
PR #9 with these changes was closed. This is not a good use case for refs.
